### ISSUE TITLE
Doesn't build with GHC8.8 and above

### ISSUE THREAD

**Issue by LightAndLight** [zenhack/haskell-supervisors#3]
The `base` upper bound needs raising. I can submit a patch when I have more time if you want, but in the meantime I'll let this sit here.

**Comment by zenhack** [comment]
I actually already did this on master, and I *thought* I made a metadata revision on hackage, but apparently not. I just did it, so if you `cabal update` you should be able to build 0.2 on ghc 8.8 now.

Thanks for prodding me about this.
